### PR TITLE
[docs] Document database creation

### PR DESCRIPTION
**Pull request by nyurik**

### CODE REVIEW

**Comment by TomPohys** [comment]
Travis failed due to https://planet.passportcontrol.net/pbf/planet-latest.osm.pbf 502 internal server error

**Comment by smellman** [comment]
I don't recommend Japan planet mirror, because it seems putting manually and no timestamp.

I use following script to check latest planet torrent from [bittorrent mirror](https://osm.cquest.org/torrents/)'s RSS.
```
echo `curl https://osm.cquest.org/torrents/rss.xml| xmlstarlet sel -t -m "/rss/channel/item/link" -n -v . |grep torrent|tail -n 1`
```

**Comment by nyurik** [comment]
I will address mirror issue in a separate PR. Thanks @smellman for the script!

**Comment by nyurik** [comment]
@smellman & @TomPohys , this was a minor bug in the downloader, and I fixed and merged it in https://github.com/openmaptiles/openmaptiles-tools/pull/219

**Pull request merged**
