### PR TITLE
Upgrade to Postgres12, latest ogr2ogr in preload

### PR DESCRIPTION
**Pull request by nyurik**
* Use PostgreSQL 12
* skip any features with errors when importing NaturalEarth data
* Just for the preload image, use the latest ogr2ogr from `sid` (unstable)

### CODE REVIEW

**Comment by Duiesel** [comment]
@nyurik Hi, Can't figure it out in what state is this PR now? Is there any problems with ogr2ogr and PG12? Or it will be merged later?

**Comment by Duiesel** [comment]
@nyurik I've tried ogr2ogr 3.0.4 with `-skipfailures` and got at least one empty `ne_10m_ocean` table as a result. So this option is useless in this case. May be this is bug in the GDAL source.

**Comment by TomPohys** [comment]
Could we close this when [#413](https://github.com/openmaptiles/openmaptiles-tools/pull/413) is already merged?

**Comment by TomPohys** [comment]
Thanks! Let's close it with regard to https://github.com/openmaptiles/openmaptiles-tools/pull/413.

**Pull request closed without merging**
