### PR TITLE
Add vars on layers (with overrides)

### PR DESCRIPTION
**Pull request by francois2metz**
I wanted to make some stuff configurable via environnement variable. So I added environnement variable substitution when collecting sql files.

### CODE REVIEW

**Comment by nyurik** [comment]
Thanks @francois2metz , this does look like an interesting idea!  I think we should not limit it to `ENV` because env variables is an implementation detail that should not be hard coded.  Instead, I think we should introduce a concept of a "variable", and have multiple ways to set that variable. Something like this:

#### In SQL file
```sql
# layers/water/water.sql
SELECT * from test where zoom > %% VAR: custom_zoom %%
```
#### In Layer yaml file
```yaml
# layers/water/water.yaml
layer:
  vars:
    custom_zoom: 10
```
#### In Tileset yaml file
```yaml
# openmaptiles.yaml
tileset:
  layers:
    - file: layers/water/water.yaml
      vars:
        custom_zoom: 12
  overrides:
    vars:
      custom_zoom: 11
```
#### ENV vars
`OMT_VAR_custom_zoom=13`

The above would work as following:
* The layer defines and uses `custom_zoom` variable. It is an error to have `%% VAR: foo %%` if `foo` default value is not set in the layer's yaml file
* Tileset can override the var globally (i.e. `10 -> 11`)
* Tileset can override the var per layer - in the example above, global override is lower priority than per-layer override, so it becomes `11 -> 12`
* Lastly the ENV var can be used to override all of the above, setting `custom_zoom` to 13.  This approach is the same as used by [Terraform](https://www.terraform.io/language/values/variables#environment-variables). Note that env var names are case-sensitive on Linux & Mac, but not on Windows.

**Comment by francois2metz** [comment]
Sound like a good idea. I'll work on it!

**Comment by nyurik** [comment]
@francois2metz i converted it to draft, please convert it back when ready. Thx!

**Comment by nyurik** [comment]
@francois2metz I think it would be easier to implement all this logic in the layer init function. Basic logic:
* create a dict of vars from the layer yaml
* get global tileset vars, and iterate over all of them.  Only override layer if it already had that var
*same for layer overrides, but raise an error if layer doesn't already define that var
* iterate over resulting dict, and try to get corresponding env vars
* store the resulting dict in self, and create a getter function

**Comment by francois2metz** [comment]
@nyurik Hi, I think I have done most of the work. I would be great to have a new review!

**Comment by francois2metz** [comment]
I updated the PR on indoor= that use this code: https://github.com/indoorequal/indoorequal/pull/30

**Comment by nyurik** [comment]
@francois2metz I have made a few proposed changes to your code -- see https://github.com/indoorequal/openmaptiles-tools/pull/1

**Comment by francois2metz** [comment]
I manually merged your PR. The only change is the name of the TestCase `TilesetTestCase` that match the name of the tested class.

**Review by nyurik — APPROVED** [review]
looks good, thanks!

**Pull request merged**
