### PR TITLE
import-wikidata now loads data from live WDQS

### PR DESCRIPTION
**Pull request by nyurik**
The `import-wikidata` tool searches for all wikidata tags in the database,
and uses Wikidata Query Service to get the labels in all languages.
This tool looks at all tables defined in layers' mapping files if they contain
`tags` hstore field, and if the table has no `_resolve_wikidata: false` flag.
The localized names are written to the `wd_names` table.

Additional minor changes:
* updated tools version
* remove duplicate tileset code

### CODE REVIEW

**Comment by MartinMikita** [comment]
Hi @nyurik,
Thanks for your work and PR. But this is not very clear and correct use of PR.

1. You have merged PR within 15 minutes, without receiving any feedback from requested reviewers.
2. You have more changes with refactoring/code cleanup, which does not correspond with import-wikidata tool.

You should be more respectful, while this is a public repository, managed by team of contributors, not only by you.

**Comment by klokan** [comment]
I am very excited about the change which may avoid downloading of very large dump from Wikipedia - as discussed on our last Hangout @nyurik. Really cool work done here... Thanks!

@MartinMikita works now on generating v3.11 - and is ready to do reviews on tools.

Any PR which represents a large change and is potentially breaking backwards compatibility does really require a proper review by others...

**Comment by nyurik** [comment]
@MartinMikita @klokan sorry, my fault - bad judgement at 3am :(  This feature should not change anything about the existing behavior, but fully agree, should have waited.

**Comment by mervynsimzr** [comment]
Is there still an option to load data from the large Wikidata dumps? Or can I import the data dump as a json cache file (#194)?

**Comment by TomPohys** [comment]
Hi @mervynsimzr, the docker image (https://github.com/openmaptiles/import-wikidata) which downloading and importing a large Wikidata dump, was deprecated and it is no longer used. Now the WDQS is used as the primary source. If you have cached `wikidata.json` from a previous run, you can run [`import-wikidata`](https://github.com/openmaptiles/openmaptiles-tools/blob/master/bin/import-wikidata#L22-L23) tool with `-c <file> -n` switchers.

**Comment by mervynsimzr** [comment]
It's my first time running so I don't have a cached prior `wikidata.json` to import. I'm also working in a firewalled environment so I would have to bring in the docker images and PBF file manually, then attempt to render the map tiles in an offline server. Ideally, it would be great to be able to bring in the Wikidata dump and import internally.

**Comment by TomPohys** [comment]
If you look at the last stable release of OpenMapTiles [3.11](https://github.com/openmaptiles/openmaptiles/tree/3.11), you should be able to make changes and import wikidata by dump. Please look at [readme](https://github.com/openmaptiles/openmaptiles/blob/3.11/README.md), [makefile](https://github.com/openmaptiles/openmaptiles/blob/3.11/Makefile#L229-L231) and [docker-compose](https://github.com/openmaptiles/openmaptiles/blob/3.11/docker-compose.yml#L81). Docker image on Docker Hub is still available for download (https://hub.docker.com/r/openmaptiles/import-wikidata)

**Comment by mervynsimzr** [comment]
Thanks @TomPohys for the suggestion! I'll give it a try, now I'm running on OpenMapTiles 5.3.

**Comment by TomPohys** [comment]
The import wikidata from the dump was done in OpenMapTiles, not in OpenMapTiles-Tools.

**Pull request merged**
